version: '2.1'
services:
   rabbitmq:
      image: rabbitmq:3
      container_name: rabbitmq

   database:
      build: ./postgres
      container_name: database
      environment:
         - PGPASSWORD=docker
         - POSTGRES_USER=docker
         - POSTGRES_PASSWORD=docker
         - POSTGRES_DB=kitdm20
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U docker -d kitdm20"]
        interval: 10s
        timeout: 5s
        retries: 15
   tomcat:
      build: ./tomcat
      container_name: tomcat
      ports: 
        - "8090:8080"
      volumes:
        - ./data:/kitdm20/data/
      depends_on:
        database:
          condition: service_healthy
        rabbitmq:
          condition: service_started  # TODO find working healthcheck
      environment:
        - DATABASE_PORT_5432_TCP_ADDR=database
        - RABBITMQ_PORT_4369_TCP_ADDR=rabbitmq 
