version: '3'
services:
    pitservice:
        build: ./pit-service
        container_name: pitservice
        ports:
        - "8091:8080"
        depends_on:
        - database
        - messagebroker
        environment:
        - DATABASE_PORT_5432_TCP_ADDR=database
        - RABBITMQ_PORT_4369_TCP_ADDR=messagebroker