version: '3'
services:
    pitservice:
        build:
            context: .
            dockerfile: ./Dockerfile_jar
            args:
              - SERVICE_FOLDER=pit-service
              - BINARY_NAME=pit-service
        container_name: pitservice
        ports:
            - "8091:8080"
        depends_on:
            - database
            - messagebroker
        environment:
            - DATABASE_PORT_5432_TCP_ADDR=database
            - RABBITMQ_PORT_4369_TCP_ADDR=messagebroker
    
    metastore2:
        build:
            context: .
            dockerfile: ./Dockerfile_jar
            args:
                - SERVICE_FOLDER=metastore2
                - BINARY_NAME=metastore2
        container_name: metastore2
        ports:
            - "8093:8080"
        depends_on:
            - database
            - messagebroker
        environment:
            - DATABASE_PORT_5432_TCP_ADDR=database
            - RABBITMQ_PORT_4369_TCP_ADDR=messagebroker
